# Generated by Django 4.2.4 on 2024-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Useremail', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
