# Generated by Django 4.2.4 on 2024-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Fitness_goal',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='members',
            name='Fitness_level',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='members',
            name='week_time',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='Useremail',
            field=models.EmailField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
