# Generated by Django 4.2.4 on 2024-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_fitness_goal_members_fitness_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='week_time',
            field=models.IntegerField(default='0'),
        ),
    ]
